### PR TITLE
Optimizing PluginUtils class

### PR DESCRIPTION
**Pull request by MAXOUXAX**
**WARNING: This has not been tested and must be tested before merging.**

Hey!
I've been refracting this class for the last two days using some Java 8 features and renaming some methods to make it more optimized.

### CODE REVIEW

**Comment by Lenni0451** [comment]
Looks good but every command is broken and has to be redone. Would be nice if you could do this. If not I'll have to do it later on

**Comment by MAXOUXAX** [comment]
Sadly I'm not planning on using this plugin but just this class, so I'm not sure I can help with that, sorry.

**Comment by MAXOUXAX** [comment]
Didn't notice that I broke all these commands because I didn't import the whole project but only this class, sorry for that.

**Comment by Lenni0451** [comment]
Ok, no Problem. I now have time to fix all the problems. Thanks again for the improvements

**Comment by Lenni0451** [comment]
Thanks again for the improvements. I manually merged the PluginUtils and fixed and tested all commands. I'll just close this pr. I put your name into the commit.

**Pull request closed without merging**
