### PR TITLE
Java 12 support

### PR DESCRIPTION
**Pull request by LaserSlime**
The current way of getting the modifiers field was patched in java 12 and causes console errors.

This adds support for Java 12 and above using a new method.
(https://stackoverflow.com/questions/56039341/get-declared-fields-of-java-lang-reflect-fields-in-jdk12)
This should still work in Java 8. Haven't tested tho.

### CODE REVIEW

**Comment by Lenni0451** [comment]
Thanks for the Info. I actually did not know about VarHandles.
Sadly this code is not Java 8 compatible as VarHandles got introduced in [Java 9](https://docs.oracle.com/javase/9/docs/api/java/lang/invoke/VarHandle.html).

It would be nice if you could come up with a solution to support both.

**Comment by LaserSlime** [comment]
I don't think there's a way if it doesn't even compile...

**Comment by Lenni0451** [comment]
I'll test around with it. Maybe there is a solution to this.

**Comment by Lenni0451** [comment]
Great news!
The code that broke Java 12 support actually was completely useless. I removed it and tested it with a Java 15 preview. Worked fine there so I assume Java 12 will work too.
Thanks for your PR anyway as I did not actually know about this.

**Comment by LaserSlime** [comment]
> 
> 
> Great news!
> The code that broke Java 12 support actually was completely useless. I removed it and tested it with a Java 15 preview. Worked fine there so I assume Java 12 will work too.
> Thanks for your PR anyway as I did not actually know about this.

I also didn't know what it was for, I just assumed it's something that needs to be fixed. Are you sure it's completely useless tho? Maybe it's like the garbage collection thing were you do something to "hope that it will prevent issues".

**Comment by Lenni0451** [comment]
Java prevents reflection access to private static fields because whoever knows. That code bypassed this check which made it able to set those Fields. But it is not needed to set static final fields in this situation so it can be replaced with a static check.
I maybe added it to prevent issues in the future if it would be needed? I don't know anymore.

The System.gc() call was a try to convince java to unload all left over classes of that plugin but as you may know that is not possible. You can not just unload classes from Java. At least to my knowledge

**Comment by Lenni0451** [comment]
In theorie this should cause ClassLoader issues because the classes are still loaded but spigot creates a new ClassLoader for every plugin preventing such issues.
If you start a normal java Thread in the onEnable() of your plugin that thread will continue to run, even if you reload the server. That is exactly why reloading is deprecated and should never be used for any production environment as it tends to break things.

**Comment by LaserSlime** [comment]
From what I know this code also breaks a lot of skin/nick plugins on java 12. Really don't know what it's needed for...

**Comment by Lenni0451** [comment]
When I tested PM after removing the code FAWE/WorldEdit broke for me too. Don't know why

**Pull request closed without merging**
